### ISSUE TITLE
Provide a deep import for each function

### ISSUE THREAD

**Issue by jaydenseric** [thekelvinliu/country-code-emoji#11]
Right now, the API is only available from index files:

https://unpkg.com/browse/country-code-emoji@2.3.0/lib/index.mjs

Ideally, `countryCodeEmoji` and `emojiCountryCode` would be available separately, e.g:

```js
import countryCodeEmoji from 'country-code-emoji/countryCodeEmoji.mjs';
```

```js
import emojiCountryCode from 'country-code-emoji/emojiCountryCode.mjs';
```

This way only the necessary code can be imported and loaded into memory in a given context, and it also ensures perfect bundling without depending on slow and unreliable "tree-shaking".

**Comment by thekelvinliu** [comment]
this to me is mainly a matter of opinion, and to be honest, i don't really agree. i suggest forking this library if you feel strongly about it.
