### ISSUE TITLE
Netherlands Antilles flag missing.

### ISSUE THREAD

**Issue by StarkHK** [thekelvinliu/country-code-emoji#17]
Hi , Can you please add Netherlands Antilles flag to your library . Thank you.

**Comment by thekelvinliu** [comment]
so the issue you are facing has more to do with emoji support and iso standards (ISO 3166-1 alpha-2). `AN` is not official/standard according to wikipedia. perhaps `CW`, `SX`, and/or `BQ` are what you want.

https://en.wikipedia.org/wiki/ISO_3166-2:AN

related: https://github.com/thekelvinliu/country-code-emoji/issues/4
