### ISSUE TITLE
Tell whether proper flag where found

### ISSUE THREAD

**Issue by lud-hu** [thekelvinliu/country-code-emoji#19]
Is there a way to tell if a proper flag was found?
In the README you write:
`
to keep things simple, if cc a two letter string, but not an actual ISO 3166-1 alpha-2 code, the regional indicator symbols corresponding to the letters in cc are returned.
`
Is there a way to see if this happened?

If so, I don't want to display the letters with the border, but just a string:
![image](https://user-images.githubusercontent.com/26108368/140740293-8ec4e719-1bcc-483e-b35c-461726b8608c.png)

**Comment by stof** [comment]
Supported flags depend on the emoji font being used. For instance, in Segoe UI Emoji (the Windows emoji font), none of the country flags are implemented, so they are *all* rendered as regional indicator symbols instead (because that's the way country flag emojis are actually implemented in Unicode)

**Comment by thekelvinliu** [comment]
ty @stof 😄 

closing bc out of scope
