### ISSUE TITLE
Not working on windows platform for chromium based browsers

### ISSUE THREAD

**Issue by gameonvinay** [thekelvinliu/country-code-emoji#24]

**Comment by stof** [comment]
The issue is not that the library is not working but that the Segoe UI Emoji (the builtin emoji font on windows) does not support flags. See https://stackoverflow.com/a/54520964

**Comment by roderickhsiao** [comment]
some fallback solution https://yarnpkg.com/package/country-flag-emoji-polyfill

**Comment by thekelvinliu** [comment]
ty @stof 😄 

closing bc out of scope
