### ISSUE TITLE
Missing country code: AN

### ISSUE THREAD

**Issue by michaeljakob** [thekelvinliu/country-code-emoji#4]
I believe the country code "AN" is missing here. It could well be that there is no emoji for this, yet. 

Review: https://www.google.com/search?q=an+country+code&oq=AN+country+&aqs=chrome.0.0j69i57j0l5j69i60.1426j1j4&sourceid=chrome&ie=UTF-8

**Comment by thekelvinliu** [comment]
the history is beyond me, but it doesn't look like `AN` will have one anytime soon 😬  https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#AN

it's tough for this library to miss because all it does is change the input code points by a certain offset 😄
